[package]
name = "leetcode"
version = "0.1.0"
authors = ["Zhirun Yan <sa615371@mail.ustc.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
